language: php
php:
- 5.5
- 5.6
env:
- DB=mysql
before_deploy:
- openssl aes-256-cbc -K $encrypted_a7742cc05c8e_key -iv $encrypted_a7742cc05c8e_iv
  -in devops.enc -out devops -d

- chmod 600 devops
deploy:
- provider: script
  skip_cleanup: true
  script: ssh -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no -tt -i devops
    ubuntu@products.arcada.nitor.zone /home/ubuntu/update.sh
  on:
    branch: master
