language: python
addons:
  firefox: 55.0.3
before_install:
- pip install -r requirements.txt
install: true
before_script:
- export DISPLAY=:99.0
- sh -e /etc/init.d/xvfb start
- sleep 3
- cd src
- python3 -m http.server &
- sleep 3
- cd -
- wget https://github.com/mozilla/geckodriver/releases/download/v0.18.0/geckodriver-v0.18.0-linux64.tar.gz
- mkdir geckodriver
- tar zxvf geckodriver-v0.18.0-linux64.tar.gz -C geckodriver
- export PATH=$PATH:$PWD/geckodriver
script:
- pybot robot


before_deploy:
- openssl aes-256-cbc -K $encrypted_744ccfe88484_key -iv $encrypted_744ccfe88484_iv
  -in frontend_key.enc -out frontend_key -d
- chmod 600 frontend_key

deploy:
  - provider: script
    skip_cleanup: true
    script: ssh -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no -tt -i frontend_key ubuntu@frontend.arcada.nitor.zone /home/ubuntu/updateApp.sh
    on:
      branch: master